# Generated by Django 5.0.2 on 2024-02-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправителя')),
                ('receiver', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('point_of_dispatch', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('point_of_receipt', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('index_dispatch', models.CharField(max_length=100, verbose_name='Индекс места отправки')),
                ('index_receipt', models.CharField(max_length=100, verbose_name='Индекс места получения')),
                ('letter_type', models.IntegerField(choices=[(0, 'Письмо'), (1, 'Заказное письмо'), (2, 'Ценное письмо'), (3, 'Экспресс-письмо')], verbose_name='Тип письма')),
                ('weight', models.IntegerField(verbose_name='Вес письма')),
            ],
            options={
                'db_table': 'letters',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправителя')),
                ('receiver', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('point_of_dispatch', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('point_of_receipt', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('index_dispatch', models.CharField(max_length=100, verbose_name='Индекс места отправки')),
                ('index_receipt', models.CharField(max_length=100, verbose_name='Индекс места получения')),
                ('phone', models.CharField(max_length=11, verbose_name='Тип посылки')),
                ('parcel_type', models.IntegerField(choices=[(0, 'Мелкий пакет'), (1, 'Посылка'), (2, 'Посылка 1 класса'), (3, 'Ценная посылка'), (4, 'Международная посылка'), (5, 'Экспресс-посылка')], verbose_name='Тип посылки')),
                ('amount', models.IntegerField(verbose_name='Сумма платежа')),
            ],
            options={
                'db_table': 'parcels',
            },
        ),
    ]
